#print_head "Remove the existing content"
#rm -rf /usr/share/nginx/html/* &>>$log_file
#func_status_check $?
#
#print_head "Download the application content"
#curl -o /tmp/frontend.zip https://roboshop-artifacts.s3.amazonaws.com/frontend.zip &>>$log_file
#func_status_check $?
#
#print_head "Extract the App content"
#cd /usr/share/nginx/html &>>$log_file
#unzip /tmp/frontend.zip &>>$log_file
#func_status_check $?
#
#print_head "Enable and restart the service"
#systemctl restart nginx &>>$log_file
#systemctl enable nginx &>>$log_file
#func_status_check $?

- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy Roboshop config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: clean old app content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: Download and archive content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes