- name: Copy Elastic Repo file
  ansible.builtin.templates:
    src: ealstic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

