- name: Load MongoDB schema
  when: schema_setup == "mongo"
  block:
    - name: Copy Mongo repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install mongodb client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed

    - name: load schema
      ansible.builtin.shell: mongo --host {{ lookup('aws_ssm', 'dev.catalogue.mongo_endpoint', region='us-east-1' ) }} </app/schema/{{component}}.js

- name: Load Mysql schema
  when: schema_setup == "mysql"
  block:
    - name: Install mysql client
      ansible.builtin.yum:
        name: mysql

    - name: load schema
      ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'dev.shipping.db_host', region='us-east-1' ) }} -u{{ lookup('aws_ssm', 'dev.shipping.db_user', region='us-east-1' ) }} -p{{ lookup('aws_ssm', 'dev.shipping.db_pass', region='us-east-1' ) }} < /app/schema/{{component}}.sql
